# -*- coding: utf-8 -*-
"""sort_object

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0uVUE1NHjXQ9-I9tOi6upPB4YaeDy4o
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse': [200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}
#x,y
sorted_keys = sorted(obj_detected, key=lambda k: obj_detected[k][0])

for key in sorted_keys:
    print(key, obj_detected[key])